### PR TITLE
Fix svg color to android color import

### LINKED ISSUE #53: SVG colors aren't being imported correctly
The below SVG incorrectly imports the fill color as `#000000ff` instead of `#ff000000`. Same thing happens with stroke colors too.

```
<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
    <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" fill="#000"/>
</svg>
```

### PR DESCRIPTION
**Pull request by alexjlockwood**
The previous code wasn't importing translucent SVG colors correctly. First, the `tinycolor2` module seems to create hex colors with the alpha bits at the end of the string (i.e. `#000000ff` instead of `#ff000000` to represent black). Second, the previous code was baking the SVG's fill and stroke opacities directly into the rgba colors. We don't want to do this; we want to let each have their own alpha channels instead.

This fixes #53.

### CODE REVIEW

File: app/scripts/svgloader.js [hunk 1]
```diff
@@ -125,9 +125,9 @@ export const SvgLoader = {
         return Object.assign(layerData, {
           id: makeFinalNodeId_('path'),
           pathData: path,
-          fillColor: ColorUtil.svgToAndroidColor(context.fillColor, context.fillOpacity),
```
Comment (romannurik) [inline app/scripts/svgloader.js:128]: hm, is fillOpacity never actually set? there's definitely a `fill-opacity` attribute in SVG AFAIK. We may need to multiple if it can appear in both the color and as a fill-opacity.

Comment (alexjlockwood) [reply app/scripts/svgloader.js:128]: Yeah, the fill opacity is assigned to the vector's `android:fillAlpha` attribute below. The RGBA color values are separate from the opacities set on the path. So for example, setting the opacity of the path *does not* alter the path's color value at all. They operate completely independently of one another. The same thing is also true with Android's `fillColor` and `fillAlpha` attributes.

Here's a sample SVG that you can try importing:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <path d="M0,0 L24,24" stroke-width="1" fill="none" stroke="rgba(0,0,0,0.5)" stroke-opacity="0.5"/>
</svg>
```

**Comment by romannurik** [comment]
Going to go ahead and merge, but Alex, mind dropping a sample SVG somewhere, e.g. in a "tests" folder or something

**Comment by alexjlockwood** [comment]
Sure, will do. One of the UXers I work with is going to send me a ton of SVGs that I think will cover a ton of cases. :D I'll make a bug to remind myself to create a tests/ folder.

BTW, if you have any suggestions on testing frameworks to use I could try setting up something basic.
